# https://nikitabobko.github.io/AeroSpace/commands
# https://nikitabobko.github.io/AeroSpace/guide
# https://nikitabobko.github.io/AeroSpace/goodies
start-at-login = true

# after-startup-command = [
#   'exec-and-forget borders active_color=0xffffffff inactive_color=0x33ffffff width=10.0 hidpi=on'
# ]

exec-on-workspace-change = ['/bin/bash', '-c',
    'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 200

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
default-root-container-orientation = 'auto'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = ['move-mouse window-lazy-center']

# automatically-unhide-macos-hidden-apps = true

[key-mapping]
    preset = 'qwerty'

# German Keyboard Mapping
[key-mapping.key-notation-to-key-code]
#    de_sharp_s = 'minus'
#    # the '´' symbol
#    de_tick = 'equal'
#    de_y = 'z'
#    de_z = 'y'
#    de_a_umlaut = 'quote'
   de_o_umlaut = 'semicolon'
#    de_u_umlaut = 'leftSquareBracket'
#    # the '#' symbol
#    de_raute  = 'backslash'
#    de_minus = 'slash'
#    de_plus = 'rightSquareBracket'
#    de_smaller = 'backtick'

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
# See:
# https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
    outer.top =        [{ monitor.'Built-in Retina Display' = 5} , 32]
    inner.horizontal = 10
    inner.vertical =   10
    outer.left =       5
    outer.bottom =     4
    outer.right =      5

[mode.main.binding]

    # All possible keys:
    # - Letters.        a, b, c, ..., z
    # - Numbers.        0, 1, 2, ..., 9
    # - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
    # - F-keys.         f1, f2, ..., f20
    # - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon,
    #                   backtick, leftSquareBracket, rightSquareBracket, space, enter, esc,
    #                   backspace, tab, pageUp, pageDown, home, end, forwardDelete,
    #                   sectionSign (ISO keyboards only, european keyboards only)
    # - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
    #                   keypadMinus, keypadMultiply, keypadPlus
    # - Arrows.         left, down, up, right

    # All possible modifiers: cmd, alt, ctrl, shift

    ctrl-alt-cmd-0 = 'layout horizontal vertical'
    ctrl-alt-cmd-shift-0 = 'layout tiles accordion'

    # Let 'focus' work when all windows are floating with custom script
    ctrl-alt-cmd-q = 'focus --boundaries-action wrap-around-the-workspace left'
    ctrl-alt-cmd-w = 'focus --boundaries-action wrap-around-the-workspace down'
    ctrl-alt-cmd-e = 'focus --boundaries-action wrap-around-the-workspace up'
    ctrl-alt-cmd-r = 'focus --boundaries-action wrap-around-the-workspace right'

    ctrl-alt-cmd-j = 'move left'
    ctrl-alt-cmd-k = 'move down'
    ctrl-alt-cmd-l = 'move up'
    ctrl-alt-cmd-de_o_umlaut = 'move right'

    ctrl-alt-cmd-shift-j = 'join-with left'
    ctrl-alt-cmd-shift-k = 'join-with down'
    ctrl-alt-cmd-shift-l = 'join-with up'
    ctrl-alt-cmd-shift-de_o_umlaut = 'join-with right'

    # See: https://nikitabobko.github.io/AeroSpace/commands#resize
    ctrl-alt-cmd-a  = 'resize smart -50'
    ctrl-alt-cmd-s = 'resize smart +50'
    ctrl-alt-cmd-d = 'balance-sizes'
    ctrl-alt-cmd-f = 'layout floating tiling'
    #    ctrl-alt-cmd-f = 'macos-native-fullscreen'

    # See: https://nikitabobko.github.io/AeroSpace/commands#workspace
    ctrl-alt-cmd-5 = 'workspace 􀖇'
    ctrl-alt-cmd-1 = 'workspace 1'
    ctrl-alt-cmd-2 = 'workspace 2'
    ctrl-alt-cmd-3 = 'workspace 3'
    ctrl-alt-cmd-4 = 'workspace 4'
#     ctrl-alt-cmd-a = 'workspace A'

    ctrl-alt-cmd-shift-5 = 'move-node-to-workspace 􀖇 --focus-follows-window'
    ctrl-alt-cmd-shift-1 = 'move-node-to-workspace 1 --focus-follows-window'
    ctrl-alt-cmd-shift-2 = 'move-node-to-workspace 2 --focus-follows-window'
    ctrl-alt-cmd-shift-3 = 'move-node-to-workspace 3 --focus-follows-window'
    ctrl-alt-cmd-shift-4 = 'move-node-to-workspace 4 --focus-follows-window'

    # See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
    ctrl-alt-cmd-tab = 'workspace-back-and-forth'
    # See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
    ctrl-alt-cmd-shift-tab = 'move-workspace-to-monitor --wrap-around next'

    # See: htps://nikitabobko.github.io/AeroSpace/commands#mode
    ctrl-alt-cmd-shift-s = 'exec-and-forget bash -c "aerospace mode service; sketchybar --trigger aerospace_mode_change INFO=service"'

    cmd-h = [] # Disable "hide application"
    # cmd-alt-h = [] # Disable "hide others"

[workspace-to-monitor-force-assignment]
        "􀖇" = [1, 'main']
        1 = ['Virtuell 16:9', 'main']
        2 = ['Virtuell 16:9', 'main']
        3 = 'main'
        4 = 'main'
        # 5 = 'main'
        # 6 = ['Immersed 2', 'main']
        # 7 = ['Immersed 2', 'main']
        # 8 = ['Immersed 2', 'main']
        # 9 = ['Immersed 1', 'main']

# 'service' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# Get current app IDs via list-apps --all command
[mode.service.binding]
    esc = ['reload-config', 'mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_change']
    r = ['flatten-workspace-tree', 'mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_change'] # reset layout

# Floating Windows
[[on-window-detected]]
    if.app-id = 'com.apple.systempreferences'
    run = 'layout floating'

[[on-window-detected]]
    if.app-id = 'com.ugreen.pro.client'
    run = 'layout floating'

# Workspace 2
[[on-window-detected]]
    if.app-id = 'com.microsoft.VSCode'
    run = 'move-node-to-workspace 2'

# Workspace 3
# Force Layout Accordion. Since Outlook is always open, it's sufficient
[[on-window-detected]]
    if.app-id = 'com.microsoft.Outlook'
    run = ['move-node-to-workspace 3', 'layout accordion']

[[on-window-detected]]
    if.app-id = 'com.microsoft.Excel'
    run = 'move-node-to-workspace 3'

[[on-window-detected]]
    if.app-id = 'notion.id'
    run = 'move-node-to-workspace 3'


# Workspace 4
[[on-window-detected]]
    if.app-id = 'com.spotify.client'
    run = 'move-node-to-workspace 4'

[exec.env-vars]
    PATH = '${HOME}/.config/aerospace_scripts:/opt/homebrew/bin:${PATH}'
